name: counter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod
  riverpod_annotation:
    path: ../../packages/riverpod_annotation

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  riverpod_generator:
    path: ../../packages/riverpod_generator
  riverpod_lint:
    path: ../../packages/riverpod_lint

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod

flutter:
  uses-material-design: true
